const initiatives = [
  { icon: "✦", title: "Education support", text: "Keeping learners in school with supplies, scholarships and mentoring.", tag: "Learn & thrive" },
  { icon: "✚", title: "Health & relief", text: "Helping families access essential care, nutrition and relief when it matters most.", tag: "Care with dignity" },
  { icon: "◎", title: "Community welfare", text: "Supporting practical, locally led work that strengthens communities.", tag: "Stronger together" },
];
const stories = [["A first-generation learner", "School supplies and encouragement can help a child stay connected to their education."], ["Care that reaches families", "Community-first relief is designed around the needs people identify on the ground."], ["Many small actions, shared hope", "Every contribution helps make long-term opportunity more possible."]];

export default function Home() {
  return <main>
    <header className="site-header"><a className="brand" href="#top" aria-label="Kautike Charitable Foundation home"><span className="brand-mark">✦</span><span>Kautike <b>Charitable Foundation</b></span></a><nav aria-label="Primary navigation"><a href="#about">About</a><a href="#initiatives">Our initiatives</a><a href="#impact">Impact</a><a href="#stories">Stories</a></nav><a className="button button-small" href="#donate">Donate now <span>→</span></a></header>
    <section className="hero" id="top"><div className="hero-glow" /><div className="hero-copy"><p className="eyebrow">Kautike Charitable Foundation</p><h1>Every contribution can help a community <em>move forward.</em></h1><p className="hero-text">We support education, health, social welfare and relief efforts so people facing hardship can access possibility with dignity.</p><div className="hero-actions"><a className="button" href="#donate">Help create change <span>→</span></a><a className="text-link" href="#about">See how we work <span>↓</span></a></div></div><div className="hero-art" aria-hidden="true"><div className="sun" /><div className="plant"><i /><i /><i /><b /></div><div className="ground" /></div><div className="hero-note"><strong>Made for impact</strong><span>Local action. Lasting change.</span></div></section>
    <section className="intro" id="about"><p className="eyebrow">Our purpose</p><h2>A more equitable future begins with <em>practical care.</em></h2><p>Kautike works alongside communities to support students, families and people in distress. We believe education, health and social support are the building blocks of meaningful, lasting progress.</p><div className="assurances"><span>✓ Community-focused</span><span>✓ Transparent giving</span><span>✓ Tax-exempt donations under 80G</span></div></section>
    <section className="initiatives" id="initiatives"><div className="section-heading"><div><p className="eyebrow">Where your help goes</p><h2>Choose the change you want to <em>make possible.</em></h2></div><a className="text-link" href="#donate">Support an initiative <span>→</span></a></div><div className="initiative-grid">{initiatives.map((item) => <article className="initiative" key={item.title}><span className="initiative-icon">{item.icon}</span><p className="card-tag">{item.tag}</p><h3>{item.title}</h3><p>{item.text}</p><a href="#donate" aria-label={`Support ${item.title}`}>Support this work <span>→</span></a></article>)}</div></section>
    <section className="approach"><div className="approach-label">Our approach</div><div><h2>Listening first. Acting together. Building <em>confidence for tomorrow.</em></h2><p>We pair immediate support with the relationships and local knowledge needed for change to endure.</p></div><ol><li><b>01</b><span>Understand the need</span></li><li><b>02</b><span>Work with communities</span></li><li><b>03</b><span>Support lasting outcomes</span></li></ol></section>
    <section className="impact" id="impact"><p className="eyebrow">Our shared impact</p><h2>When we work together, <em>possibility grows.</em></h2><div className="impact-grid"><div><strong>50,000+</strong><span>lives reached through our work</span></div><div><strong>200+</strong><span>education programmes supported</span></div><div><strong>75+</strong><span>healthcare initiatives enabled</span></div></div><p className="impact-note">Impact figures reflect the Foundation’s cumulative programme reporting. Detailed project updates and financial information will be published as initiatives are completed.</p></section>
    <section className="stories" id="stories"><div className="section-heading"><div><p className="eyebrow">Stories of change</p><h2>Small steps can create a <em>brighter path.</em></h2></div></div><div className="story-grid">{stories.map(([title, text], index) => <article className="story" key={title}><div className={`story-image story-${index + 1}`}><span>{index === 0 ? "Learn" : index === 1 ? "Care" : "Hope"}</span></div><p className="card-tag">Community update</p><h3>{title}</h3><p>{text}</p><a href="#donate">Read the story <span>→</span></a></article>)}</div></section>
    <section className="donate" id="donate"><div><p className="eyebrow">Take part today</p><h2>Help turn care into <em>meaningful action.</em></h2><p>Your contribution supports programmes across education, health, welfare and relief. Every amount matters.</p></div><div className="donation-card"><p>Choose a starting amount</p><div className="amounts"><button>₹500</button><button>₹1,000</button><button>₹2,500</button></div><a className="button" href="/donate">Continue to donate <span>→</span></a><small>Secure online donations · 80G tax-exemption support</small></div></section>
    <footer><a className="brand footer-brand" href="#top"><span className="brand-mark">✦</span><span>Kautike <b>Charitable Foundation</b></span></a><p>Promoting education, health, social welfare, relief and the well-being of humanity.</p><div><a href="/about">About</a><a href="/initiatives">Initiatives</a><a href="/contact">Contact</a><a href="/privacy">Privacy</a></div><small>© 2026 Kautike Charitable Foundation. Mumbai, Maharashtra, India.</small></footer>
  </main>;
}
